[package]
name = "tulisp-async"
version = "0.1.0"
edition = "2024"
description = "Runtime-agnostic async primitives for tulisp."
license = "GPL-3.0"

[dependencies]
tulisp = { git = "https://github.com/shsms/tulisp", branch = "fmt", features = ["sync"] }
tokio = { version = "1", features = ["rt", "time", "sync"], optional = true }

[features]
default = ["tokio"]
tokio = ["dep:tokio"]

[dev-dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }

[[example]]
name = "sleep"
path = "examples/sleep.rs"
required-features = ["tokio"]

[[example]]
name = "heartbeat"
path = "examples/heartbeat.rs"
required-features = ["tokio"]

[[example]]
name = "channel"
path = "examples/channel.rs"
required-features = ["tokio"]

[[example]]
name = "std_executor"
path = "examples/std_executor.rs"
